name: g3m
description: G3 Model Language
version: 0.0.2

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  mustache: ^1.1.1
  path: ^1.6.4
  injector: ^1.0.8
  prompts: ^1.3.1
  args: ^1.6.0
  colorize: ^2.0.0
  inflection2: ^0.4.3

dev_dependencies:
  quiver: ^2.1.3
  pedantic: ^1.8.0
  test: ^1.6.0
